# Generated by Django 5.2.14 on 2026-05-07 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50, unique=True)),
                ('zone_name', models.CharField(max_length=100)),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('slot_type', models.CharField(choices=[('regular', 'Regular'), ('disabled', 'Disabled'), ('electric', 'Electric')], default='regular', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('floor', models.IntegerField(default=1)),
                ('row', models.PositiveIntegerField(help_text='Grid row index for navigation')),
                ('col', models.PositiveIntegerField(help_text='Grid column index for navigation')),
                ('camera', models.ForeignKey(blank=True, help_text='الكاميرا المسؤولة عن مراقبة هذا المكان', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_slots', to='parking.camera')),
            ],
            options={
                'ordering': ['floor', 'row', 'col'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='رقم اللوحة')),
                ('reservation_code', models.CharField(max_length=10, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('entry_image', models.ImageField(upload_to='entry_pics/%Y/%m/%d/')),
                ('exit_image', models.ImageField(blank=True, null=True, upload_to='exit_pics/%Y/%m/%d/')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('car_embedding', models.JSONField(blank=True, null=True)),
                ('car_color', models.CharField(blank=True, max_length=30, null=True)),
                ('is_inside', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('moving', 'Moving'), ('parked', 'Parked'), ('exited', 'Exited')], default='moving', max_length=10)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.camera')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingslot')),
            ],
            options={
                'indexes': [models.Index(fields=['is_inside', 'last_seen'], name='parking_veh_is_insi_edde63_idx')],
            },
        ),
    ]
